### ISSUE TITLE
Allow a function to be provided for the `$body`

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#110]
@ChristianGruen I think we previously discussed allowing the user to supply a `function()` for the `$body` parameter.

This would allow users to also have control over when the body is constructed, which could lead to some greater flexibility with regards streaming or processing large entity bodies.

If you are okay with that? I can easily add the text to also allow a `function()` for the `$body` alongside the other types that we currently accept... When evaluated the `function()` has to return one of the other concrete types which are acceptable when evaluated.

**Comment by ChristianGruen** [comment]
Yeah, I remember your idea of allowing function as body arguments!

We could do that… Although I would still have some tendency to let the implementations take care of lazy processing exclusively. Maybe because I’m not aware of any other extensions functions so far that impose this optimization job to the XQuery developer (and there could be numerous examples once we start to do that). Are there such functions e.g. in the eXist modules?

Maybe we can find a good example for a query that cannot be optimized – or is mostly likely not to be optimized – by an XQuery processor, and add this query to the specification?

**Comment by adamretter** [comment]
So my idea was not to "impose this optimization job to the XQuery developer", rather it was for the processor to be the normal source of optimizations. However, there are cases when the developer knows better than the processor, so I thought in those instances, the user could supply a function to force lazy-evaluation or an expensive operation.

**Comment by ChristianGruen** [comment]
Some additions to put my thoughts across:

* The implementation for supporting function item arguments should be rather trivial (at least for all implementations that provide HOF support anyway).
* I was mostly wondering in which cases the execution time and memory consumption would actually differ at all if we add function items to the spec. I guess this is mostly an implementation issue. In BaseX, I believe the performance would be pretty much identical, no matter if I specify bodies as function items or in their final representation:

```xquery
(: Both variants will provide a lazy item, and the actual file contents will be
 : requested later and streamed to the server. :)
http:post($url, file:read-binary($file)),
http:post($url, function() { file:read-binary($file) })

(: In both cases, the data will be serialized completely once the body is evaluated.
 : We don’t have a streamable implementation of fn:serialize right now;
 : if we had, performance would be similar to the first query. :)
http:post($url, serialize(<a/>)),
http:post($url, function() { serialize(<a/>) })

(: Same performance again (…in BaseX…), no matter if the function item will be invoked
 : by the user or by the HTTP Client implementation. :)
http:post($url, function() { 'do-it' })
http:post($url, function() { 'do-it' }())
```

I assume that the implementation of built-in (or statically defined) functions differs in eXist-db? Or maybe there are other query patterns that I overlooked?

**Comment by adamretter** [comment]
Let's just consider these two variants for now:

1. `http:post($url, file:read-binary($file))`
The process here is: The processor has to read the binary file (either eagerly, or lazily), and then pass the value or reference to the underlying implementation of the `http:post` function.

2. `http:post($url, function() { file:read-binary($file) })`
This variant, allows more wiggle room by the processor. For example, the processor could open a TCP socket to the web server, invoke the function to stream the request body to the server, then close the TCP socket. However, let's say the network is down or the server is not available, the processor now has less work to do, it attempts to open the TCP socket, fails and raises an error; It never had to ready the binary file (either eagerly or lazily).

Now, of course in eXist-db (and I suspect BaseX), we can assume that `file:read-binary` will be lazily evaluated, and so the file will never be opened and read until the content is actually needed.

AFAIK there is nothing in any spec that says how file:read-binary should be evaluated: lazily or eagerly.

---

I wonder what happens for other function expressions? For example, if we have:

```xquery
declare function local:get-huge-xml() as document-node() {
...
};

http:post($url, local:get-huge-xml()),
```

Is `local:user-defined-heavy-function()` also evaluated lazily in BaseX?
In eXist-db, I think `local:user-defined-heavy-function()` will be evaluated, and then the document-node() will be passed to the `http:post` function.

This may be an implementation detail, I might even be confusing myself at this point!?!

**Comment by ChristianGruen** [comment]
> Is `local:get-huge-xml()` also evaluated lazily in BaseX?

In BaseX, I can defer evaluation of an argument (such as `local:get-huge-xml()`) until its value is actually required. In our HTTP Client implementations,

1. We could evaluate the argument after the connection check.
2. We could always wrap the body argument into a function item (e.g. in a compilation step, or directly at the time where the function is called; in both cases without the user noticing it) and evaluate it afterwards. This could be an option later on if our shared implementation will have features to process the body in a lazy or streamable fashion.

So I guess that may be different in eXist-db? For example, if `fn:sum($numbers, $default)` is evaluated, `$default` will always be evaluated, is that right?

There are actually two optimizations that I mentioned in this issue without clearly separating them:

1. Arguments of built-in functions will only be evaluated if their value is required.
2. Values of [lazy items](http://docs.basex.org/wiki/Lazy_Module) (as we call them in BaseX) are streamable (and will thus consume constant memory). This wouldn’t be possible for `local:get-huge-xml()` – unless this function returns a „lazy item” (e.g. as a result of another built-in function).

**Comment by adamretter** [comment]
@ChristianGruen Okay, so I think we could park this issue as a consideration for the future.

It sounds like we could improve some optimizations in eXist-db to  get most of what I had in mind.
