### ISSUE TITLE
Is the http:send-request function included or sign-posted?

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#111]
The following text:

> The legacy function http:send-request is still available; it is explained in detail in the original HTTP Client Module.

Is somewhat ambiguous to me. It is not clear whether it means either:
1. Implementations of HTTP Client Module 2.0 must also implement `http:send-request` (in accordance with version 1.0) in their HTTP Client Module 2.0.
2. Users of the HTTP Client Module 2.0, can still use HTTP Client Module 1.0 if they need to.

Personally I think it should mean (2). As the two modules share the same namespace, and the function signatures do not clash, if my implementation (e.g. eXist-db) provides HTTP Module 1.0 and HTTP Module 2.0, then to the user there is no difference between (1) and (2).

My justification is that, implementers should be free to offer their clients either:
- Just HTTP Client Module 1.0
- HTTP Client Module 1.0 and HTTP Client Module 2.0
- Just HTTP Client Module 2.0

By adopting (2) we permit that freedom of choice. Thismeans that a new processor need only implement HTTP Client Module 2.0, and would not be forced to also implement the legacy`http:send-request` from HTTP Client Module 1.0.

**Comment by ChristianGruen** [comment]
From the user perspective, it is important that `http:send-request` is still available. From the implementation perspective, I agree there will be no need to reimplement `http:send-request` if it’s still accessible under the same namespace.

**Comment by adamretter** [comment]
@ChristianGruen I agree with your comments. However, it is still not clear to me what that means for the specification and implementers.

If you implement just the `2.0` version, does that force you to also implement the legacy `http:send-request`?

**Comment by fgeorges** [comment]
By the claim in the intro to be backward compatible, I would say yes.  Now, nothing prevent someone to implement the "entire spec", except for that one function...

I could see a note or appendix saying that the function is part of the spec, and so both implementation can live together, and users can use both at the same time, but also that if the processor never implemented 1.0 and do not see any benefit for its users to do so, then it is allowed to do so (AKA implementation-defined).

The alternative would be not to include it in 2.0, and say it is NOT backward compatible with 1.0, in the sense that you cannot run a transform or query written for 1.0 with 2.0.  But also emphasize that by using another function name, then implementations of both versions of the spec can be used side by side with no problem, would an implementation provide both.

**Comment by adamretter** [comment]
> By the claim in the intro to be backward compatible, I would say yes.

The text does not claim to be "backward compatible", it actually says "backward-compliant". We don't want to be *backward compatible*, and we intentionally designed with that in-mind, as we felt that otherwise there would be too many barriers to improving the experience.

> I could see a note or appendix saying that the function is part of the spec, and so both implementation can live together, and users can use both at the same time, but also that if the processor never implemented 1.0 and do not see any benefit for its users to do so, then it is allowed to do so (AKA implementation-defined).

I don't see how that is any different from not explicitly forcing 2.0 implementers to add the `http:send-request` function from 1.0. If it remains solely in 1.0, which I think it should, this still allows them to both live together, and users can use both (1.0 and 2.0) at the same time.

> The alternative would be not to include it in 2.0, and say it is NOT backward compatible with 1.0
Again, we never said "backward compatible". I think the wording of "backward-compliant" was probably chosen very carefully.

All I am asking is that we further expand in the text on what "backward-compliant" means, so that we don't have discussions like the above amongst our users ;-)

IMHO It is simple enough to say, something like the following in the spec:

We define "*backward-compliant*" to mean that the 2.0 and 1.0 versions of HTTP Client Module live in harmony side-by-side, that is to say that their functions, etc. are all in the same namespace. We have intentionally designed 2.0 so that it does not override, replace, or conflict, with any specific behaviour of 1.0. Rather, 2.0 complements 1.0, providing a fresh API for newer versions of XPath. The design, allows users to conveniently use either version, or to use both 2.0 and 1.0 versions together should they wish.
