### ISSUE TITLE
ReSpec - Latest published version must NOT be in TR dir

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#113]
Using ReSpec, the "Latest published version:" at the top of the document is `https://www.w3.org/TR/{spec-name}/`.  Which is correct for W3C Recommendations from WG, not for Reports from CG.

Find a way to change it.

Take into account that it does not seem we have a "non-dated" URL for CG final reports (that is, the one URL of the report is `https://www.w3.org/YYYY/MM/expath-{spec-name}-YYYYMMDD/`.

**Comment by fgeorges** [comment]
There are actually 2 spec status dedicated to Community Groups: `CG-DRAFT` and `CG-FINAL`:

    specStatus: "CG-DRAFT",

But then, that is the other way around: when using `CG-FINAL`, the only URL is "latest editor draft", and there is no "latest published version".

**Comment by fgeorges** [comment]
I got a working version in `specs/http-client/`, except for:

- with `specStatus = CG-FINAL`, the final URL is still the draft URL
- the "Commit history" link results in a 404 (to `.../commits/gh-pages` on GitHub which does not exist)

**Comment by fgeorges** [comment]
Email sent to Ian/teams-community-process about the last details before publication.

**Comment by ChristianGruen** [comment]
Hi @fgeorges, did you get any feedback on this?

**Comment by fgeorges** [comment]
Hi @ChristianGruen, thank you for the reminder.  Here is a summary of the responses I've got from Ian:

- use `specStatus: "CG-DRAFT"` and `publishDate: "2018-09-01"`
- in order to have it published, write to team-community-process@w3.org

He also said:

> What I don’t know how to do is get a “This Version” URL.  Indeed, this example of a final report <https://www.w3.org/2017/05/vc-use-cases/CGFR/2017-05-01/> similarly shows a "Latest editor's draft” URI, but the document itself was published at a (different) dated URL.  Perhaps that will suffice here as well.

I will mention it when asking the team to have it published.
