### ISSUE TITLE
Publish HTTP Client 1.0

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#126]
@adamretter @ChristianGruen - Are you happy with the current version?

Notes to myself:

- `publishDate: "2018-09-01"` might need to be adapted with the final date
- in order to have it published, write to team-community-process@w3.org

Ian said, about the URL of the final report (mention it in the email):

> What I don’t know how to do is get a “This Version” URL.  Indeed, this example of a final report https://www.w3.org/2017/05/vc-use-cases/CGFR/2017-05-01/ similarly shows a "Latest editor's draft” URI, but the document itself was published at a (different) dated URL.

**Comment by ChristianGruen** [comment]
Looks fine; it’s great to see the spec finalized!

**Comment by fgeorges** [comment]
ETA is now Nov. 20.  Hopefully more details from W3C very soon.

**Comment by fgeorges** [comment]
That's it, it has been published!

See https://www.w3.org/community/expath/ and https://www.w3.org/2018/11/http-client-20181120.html.
