### ISSUE TITLE
Define "current working directory" in the File module

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#48]
Add the "definition" for "current working directory" in 2.2, saying
it's implementation-defined.

For context, see the minutes of the meeting in Prague in Feb. 2015:
https://lists.w3.org/Archives/Public/public-expath/2015Feb/0005.html

**Comment by ChristianGruen** [comment]
Thanks for adding the GitHub entries. One more things (as personal reminder): Revise description text for `file:children`.

**Comment by ChristianGruen** [comment]
Resolved (22492085246d90a8fcfd3b33b2aaf1bb34a3065a).
