### ISSUE TITLE
Migrate wiki content from EXPath to W3C

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#61]
Update (merge) the wiki at W3C with the content from expath.org, to be
sure no information is lost.

For context, see the minutes of the meeting in Prague in Feb. 2015:
https://lists.w3.org/Archives/Public/public-expath/2015Feb/0005.html

**Comment by ChristianGruen** [comment]
I have just started to move some of the contents to the new Wiki.

**Comment by ChristianGruen** [comment]
I have moved all contents to the new Wiki (except for http://wiki.expath.org/wiki/Engines), and I believe the old Wiki can be closed.

**Comment by fgeorges** [comment]
Thanks!  I had started to move some stuff myself.  Especially the Engines page and the Modules list :-)  I had a look at the [pages you created](https://www.w3.org/community/expath/wiki/Special:RecentChanges) and the [existing pages](http://wiki.expath.org/wiki/Special:AllPages) on the (soon-to-be) legacy wiki.

**Conclusion**: I think everything is there!  Below are my notes, which should not be of any use anymore, but just in case...  I will change the links to the W3C wiki, and will remove the wiki software at some point...

Thanks for your help!

The pages I saw you created:

- Saxon
- ZIP Module/Saxon
- ZIP Module
- Draft Buffer
- CXAN
- Process
- Specification
- Editors
- Webapp Module/Saxon
- Webapp Module
- Packaging Module/Saxon
- Packaging Module
- HTTP Client Module/Saxon
- HTTP Client Module
- Geo Module

Existing pages in the main namespace on http://wiki.expath.org/:

- CXAN
- Crypto
- DraftBuffer
- EXPath
- Editor
- Engines
- Geo
- HttpClient
- Main Page
- Packaging
- Specification
- Webapp
- Zip

Namespace EXPath:

- Privacy policy
- Process

Namespace Category:

- Todo

Namespace Saxon:

- Home
- HttpClient
- Packaging
- Webapp
- Zip

So the legacy pages map as following to the new pages (including already-existing pages):

- [CXAN](http://wiki.expath.org/wiki/) → [CXAN](http://w3.org/community/expath/wiki/CXAN)
- [Crypto](http://wiki.expath.org/wiki/Crypto) → [Crypto](http://w3.org/community/expath/wiki/Crypto)
- [DraftBuffer](http://wiki.expath.org/wiki/DraftBuffer) → [Draft Buffer](http://w3.org/community/expath/wiki/Draft Buffer)
- [EXPath](http://wiki.expath.org/wiki/EXPath) → [Main_Page](http://w3.org/community/expath/wiki/Main_Page)
- [Editor](http://wiki.expath.org/wiki/Editor) → [Editors](http://w3.org/community/expath/wiki/Editors)
- [Engines](http://wiki.expath.org/wiki/Engines) → [Engines](http://w3.org/community/expath/wiki/Engines)
- [Geo](http://wiki.expath.org/wiki/Geo) → [Geo Module](http://w3.org/community/expath/wiki/Geo Module)
- [HttpClient](http://wiki.expath.org/wiki/HttpClient) → [HTTP Client Module](http://w3.org/community/expath/wiki/HTTP Client Module)
- [Packaging](http://wiki.expath.org/wiki/Packaging) → [Packaging Module](http://w3.org/community/expath/wiki/Packaging Module)
- [Specification](http://wiki.expath.org/wiki/Specification) → [Specification](http://w3.org/community/expath/wiki/Specification)
- [Webapp](http://wiki.expath.org/wiki/Webapp) → [Webapp Module](http://w3.org/community/expath/wiki/Webapp Module)
- [Zip](http://wiki.expath.org/wiki/Zip) → [ZIP Module](http://w3.org/community/expath/wiki/ZIP Module)
- [EXPath:Privacy policy](http://wiki.expath.org/wiki/EXPath:Privacy policy) → [the W3C original page](http://www.w3.org/Consortium/Legal/privacy-statement-20000612) (non-wiki)
- [EXPath:Process](http://wiki.expath.org/wiki/EXPath:Process) → [Process](http://w3.org/community/expath/wiki/Process)
- [Category:Todo](http://wiki.expath.org/wiki/Category:Todo) → [the GitHub issue manager](https://github.com/expath/expath-cg/issues) (non-wiki)
- [Saxon:Home](http://wiki.expath.org/wiki/Saxon:Home) → [Saxon](http://w3.org/community/expath/wiki/Saxon)
- [Saxon:HttpClient](http://wiki.expath.org/wiki/Saxon:HttpClient) → [HTTP Client Module/Saxon](http://w3.org/community/expath/wiki/HTTP Client Module/Saxon)
- [Saxon:Packaging](http://wiki.expath.org/wiki/Saxon:Packaging) → [Packaging Module/Saxon](http://w3.org/community/expath/wiki/Packaging Module/Saxon)
- [Saxon:Webapp](http://wiki.expath.org/wiki/Saxon:Webapp) → [Webapp Module/Saxon](http://w3.org/community/expath/wiki/Webapp Module/Saxon)
- [Saxon:Zip](http://wiki.expath.org/wiki/Saxon:Zip) → [ZIP Module/Saxon](http://w3.org/community/expath/wiki/ZIP Module/Saxon)

**Comment by fgeorges** [comment]
I guess that now, we need to make sure we maintain it properly, and we organise it better (creating more pages listing or organising pages on the wiki).

Note also that this creates de facto a naming scheme for the pages on the wiki: `Foobar Module` for modules, and `Foobar Module/Saxon` for instance, for a Saxon-specific page of a module (or any other processor).

**Comment by ChristianGruen** [comment]
Florent, thanks for "post-documenting" my changes!
