### ISSUE TITLE
Shut down the wiki on expath.org

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#63]
Shut down the wiki on expath.org and remove the related software from
the server.

For context, see the minutes of the meeting in Prague in Feb. 2015:
https://lists.w3.org/Archives/Public/public-expath/2015Feb/0005.html

**Comment by ChristianGruen** [comment]
Should be possible now... #61

**Comment by ChristianGruen** [comment]
Is someone still working on these issues?

**Comment by fgeorges** [comment]
Thank you for the reminder, @ChristianGruen!  I've just adapted the links on http://expath.org/.  The old wiki should not be referred to from anywhere now.

**Comment by ChristianGruen** [comment]
And thanks for updating the links; I have closed #62 as well.
