### ISSUE TITLE
file:last-modified test

### ISSUE THREAD

**Issue by benibela** [expath/expath-cg#71]
EXPath-file-last-modified-001 and EXPath-file-last-modified-002 test if the modification time of a file is within a 0s .. +10s interval relative to the current time.

But on a FAT system the modification time has a resolution of 2s, so it rather should test for an  -2s .. +10s interval.

**Comment by michaelhkay** [comment]
Makes sense. Do we have a process for fixing this?

Michael Kay
Saxonica

**Comment by ChristianGruen** [comment]
> Do we have a process for fixing this?

Not really. However, I have just fixed these two test cases and merged my own pull request.

**Comment by fgeorges** [comment]
Thank you, @ChristianGruen. Yes, that is the idea, just fix it when a solution has been identified and double-checked.
