### ISSUE TITLE
HTTP Client 2 should not treat HTTP Options response differently

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#74]
From the HTTP 1.1 spec the relevant parts of https://tools.ietf.org/html/rfc2616#section-9.2:

> A 200 response SHOULD include any header fields that indicate
> optional features implemented by the server and applicable to that
> resource (e.g., Allow)

> The response body, if any, SHOULD also include
> information about the communication options.

> If no response body is included, the
> response MUST include a Content-Length field with a field-value of
> "0".

If I understand this correctly, it means that HTTP Options can return response headers that are important to the caller as well as a body. As such I think that `http:options` should have the same response format as e.g. `http:get`.

**Comment by ChristianGruen** [comment]
Good catch, thanks. I’ll be happy to treat this function identically to the others.
