### ISSUE TITLE
Should HTTP Client 2 use xs:anyURI for $uri?

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#75]
Discuss:

Pros and cons of using `xs:anyURI` vs `xs:string` for the `$uri` parameter of the HTTP Client 2 functions.

I am always a little uneasy when I see URIs expressed as strings when we have a data type specifically for that purpose. However, there is perhaps some convenience in using strings due to type promotion rules in the XQuery spec?

**Comment by ond1** [comment]
Hi, 

If we use xs:string for the type $uri would we be able to easily detect errors at the earliest opportunity?

In the expath http-client spec for the http:send-request function we mention the following:

> $href is the HTTP or HTTPS URI to send the request to. It is an xs:anyURI, but is declared as a string to be able to pass literal strings (without requiring to explicitly cast it to an xs:anyURI).

I guess something similar could apply.

**Comment by ChristianGruen** [comment]
Hi O’Neil, glad to see you joining in!

>> $href is the HTTP or HTTPS URI to send the request to. It is an xs:anyURI, but is declared as a string to be able to pass literal strings (without requiring to explicitly cast it to an xs:anyURI).
> I guess something similar could apply.

Exactly, this is what I would have said. When writing the spec, I relied on the original spec indeed, and I omitted various details that are already specified in that document.

> If we use xs:string for the type $uri would we be able to easily detect errors at the earliest opportunity?

My experience was that XQuery processors seem to parse `xs:anyURI` differently. For example, Saxon raises no error for the query `xs:anyURI(':')` (which is most probably correct?), but eXist-db, BaseX or Zorba seem to do so. As a result, parsing URIs in the HTTP Client Module may be implementation-specific as well.

**Comment by ond1** [comment]
> On 7 Aug 2018, at 13:24, Adam Retter <notifications@github.com> wrote:
> 
> Happy to stick with an xs:string.
> 
> When looking at the HTTP Client 1 spec -
> 
> $href is the HTTP or HTTPS URI to send the request to. It is an xs:anyURI, but is declared as a string > to be able to pass literal strings (without requiring to explicitly cast it to an xs:anyURI).
> 
> It seems to me that whilst it makes this assertion, it does nothing to validate it or even enforce it. I think we can do better in HTTP Client 2.
> 
> It would seem to me that if we want to use $uri as xs:string type in the same manner as the version 1 module, it makes sense to explicitly say that the $uri as xs:string has to be a equivalent to a valid xs:anyURI, as defined by$string castable as xs:anyURI.
> 
> 

Yes I agree we would need to make the statement more precise.



> If so, we then need to decide what error to raise if our HTTP Client functions are given an invalid URI (in the form of an xs:string). In XQuery an invalid cast would raise err:XPTY0004 or err:FORG0001. However, I think it more sensible here to use our own error code, because (a) it makes it easier for the user to understand the problem is with the http client module, and (b) otherwise we might as well use xs:anyURI and let the XQuery engine determine if and where a err:XPTY0004 or err:FORG0001 occurs.
> 
> 

Yes I agree with this too. An invalid cast error would be confusing. Some error code specific to the HTTP client is best here.

**Comment by ChristianGruen** [comment]
I’ll be fine with all solutions. My only concern is that if we decide to introduce a custom HTTP error code, the behavior would still be implementation-specific. For example, if a processor accepts `:` as valid `xs:anyURI` value, no HTTP error will be raised when parsing the URL, but any other error will most probably raised if the actual URL connection is created.

**Comment by adamretter** [comment]
@ChristianGruen hmmm. I wonder if we just need more error codes. i.e. an implementation should try to avoid returning implementation specific error code, and instead fit all errors that occur within the http client module inside the range of error codes that we define?

**Comment by ChristianGruen** [comment]
Or we try to keep it simple and add things like that in a 2.1 version?

**Comment by adamretter** [comment]
@ChristianGruen I think I could write something up that is simple ;-)

Probably best to do it at the same time that we take care of the error codes.

**Comment by michaelhkay** [comment]
> My experience was that XQuery processors seem to parse xs:anyURI differently. For example, Saxon raises no error for the query xs:anyURI(':') (which is most probably correct?), but eXist-db, BaseX or Zorba seem to do so. As a result, parsing URIs in the HTTP Client Module may be implementation-specific as well.
> 
> 

The rules for xs:anyURI change from XSD 1.0 to XSD 1.1, and in Saxon it depends which XSD version is enabled.

Michael Kay
Saxonica

**Comment by fgeorges** [comment]
@adamretter Not sure what you mean by "validate or enforce it" in the following:

> It seems to me that whilst it makes this assertion, it does nothing to validate it or even enforce it. I think we can do better in HTTP Client 2.

The whole reason for this rule is that if you make the function defined with `xs:anyURI`, then you cannot call it with a string.  Which will be the vast majority of the cases.  This is why the XPath, XQuery and XSLT specs use xs:string where a URI is expected, AFAIK.

E.g. in the following code, all function calls are OK except the 3d one (calling `g()` with a string whilst it expects a URI):

```
declare function local:f($s as xs:string) {
   $s
};

declare function local:g($s as xs:anyURI) {
   $s
};

local:f('http://example.org/'),
local:f(xs:anyURI('http://example.org/')),
local:g('http://example.org/'),
local:g(xs:anyURI('http://example.org/'))
```

**Comment by fgeorges** [comment]
Also, I forgot to mention that if you go for 3.1, we have union types now (or is it only for XSLT 3.1?)

So we could define the simple type `http:uri` as the union of `xs:string` and `xs:anyURI`.  No need for an actual schema to be explicitly loaded by the user, the spec can simply define that that type is part of the known types, and voila (even if personally, I don't see the benefit of using `xs:anyURI` at all over `xs:string`.)
