### ISSUE TITLE
HTTP Client 2 should allow for Certificate authentication

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#76]
As well as basic and digest auth, we should allow for certificate based authentication.

**Comment by adamretter** [comment]
I would like to see this included.

Perhaps we need to set a time-frame for the spec, so that we can decide what goes in and what does not?

**Comment by ChristianGruen** [comment]
> Perhaps we need to set a time-frame for the spec, so that we can decide what goes in and what does not?

Sorry, I forgot about this… What about end of September?

I’ll be offline from Sep 1 to Sep 23, but I’ll give my best next week.

**Comment by adamretter** [comment]
From now until the 20th will be a bit busy for me as I have the XML Summer School. I will try and stay responsive to discussions, but time to work on this will be limited. Perhaps we could say Mid-October?

**Comment by ChristianGruen** [comment]
Fine as well!
