### ISSUE TITLE
HTTP Client 2 improve data types for parameters and response

### ISSUE THREAD

**Issue by adamretter** [expath/expath-cg#79]
1. Could `$options` could be more strictly typed?
    Instead of `map(*)` I think we could use `map(xs:string, item())`

2. I think `$response` could be more strictly typed?
    Instead of `map(*)` I think we could use `map(xs:string, item())`

I am wondering if we should use `item()?` for the value of the map. i.e. is there a case when the server can return a key but not a value, and that has meaning as opposed to omitting both the key and value.

**Comment by ChristianGruen** [comment]
> 1. Could `$options` could be more strictly typed?
>    Instead of `map(*)` I think we could use `map(xs:string, item())`

No objection here. In the first draft, I used a stricter typing in the function signatures; the only reason I removed it was to make the signatures more readable. But I’ll fine to see them readded.

> 2. I think `$response could be more strictly typed?
>    Instead of `map(*)` I think we could use `map(xs:string, item())`
>
> I am wondering if we should use `item()?` for the value of the map. i.e. is there a case when the server can return a key but not a value, and that has meaning as opposed to omitting both the key and value.

The body value can be empty indeed, unless we drop the `body` key as well. Just a guess, but maybe it’s recommendable to always return the `body` key. There may be reasons in which a user expects a body, although none is returned. What do you think?

**Comment by adamretter** [comment]
If there is no body in the HTTP response, there seems little point having a key with an empty value in the map to represent it. I think by omission we can infer that there was no body.

Unless it is easier to query one way or the other?

**Comment by ChristianGruen** [comment]
I’m fine with that. Thanks to the semantics of paths and maps, it indeed makes no difference when writing queries.

**Comment by deblock** [comment]
I'd agree - only include the 'body' entry in $response if there is a response body. (That's what we do
in the Saxon-JS HTTP client.)
