### ISSUE TITLE
Compatility of HTTP Client 2

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#92]
@adamretter, @ChristianGruen, thank you for your work on the new HTTP Client!  At the beginning, we can read:

> It is backward-compliant with version 1.0 of the HTTP Client Module and has been designed to be compatible with [XQUERY-31] and [XPATH-31]. 

1) it does not seem backward compatible at all with 1.0 to me (the one function from 1.0 is not in the new module, which makes use of maps everywhere)

2) what about "compatible with XPath 3.1 (and thus XQuery 3.1 and XSLT 3.0)"?

Does that mean it is on purpose excluding everything that is not XPath 3.1?  The use of maps, very convenient indeed, could be solved by allowing options to be either a map, or an element with children of the same name than the map properties.

**Comment by adamretter** [comment]
**Personally** I don't have the goal of backwards compatibility. I want to create something better.

For the user, they can use http client and http client 2 modules side by side if they want backwards compatibility because the functions are in the same namespace.

I don't know how @christiangruen feels about this?

**Comment by joewiz** [comment]
@fgeorges See http://expath.github.io/expath-cg/specs/http-client2/#functions:

> The legacy function `http:send-request` is still available; it is explained in detail in the original HTTP Client Module.

Users can simply click on the link to the 1.0 spec to find the relevant function documentation.

**Comment by adamretter** [comment]
As @joewiz said! :-)

**Comment by fgeorges** [comment]
Thank you @joewiz.  My bad, I only went through the list of functions and missed that bit.

@ChristianGruen The body is a separate argument (at least can be) and in the result of http:send-request, they are separate items in the returned sequence.  So I am bit surprised that the XML representation itself is a problem at all.

That been said, the solution I suggest above works for the "input $options" (the user decides whether it provides map or XML, or maybe it is on pre-3.0 do they do not have the map option.)  But indeed, the result of the function is different.

That problem has been solved in 1.0 by returning a sequence (first the HTTP infos, like status, headers, etc., then the body, or several bodies in case of multipart.)  But I can see that maps are a more elegant way to solve that problem.

The cost of using them though, is not being compatible with pre-3.1.  Just saying that that choice must be made explicitly.

**Comment by adamretter** [comment]
I don't see any value argument for being compatible with XPath 1.0 in this new spec.

All modern processors that are actively maintained that I know of, support XPath 3.1. For XPath 1.0 legacy users, there is the legacy HTTP Client 1.0.

What positive arguments are there for making everything XPath 1.0 compatible?

**Comment by ChristianGruen** [comment]
> @ChristianGruen The body is a separate argument (at least can be) and in the result of http:send-request, they are separate items in the returned sequence.  So I am bit surprised that the XML representation itself is a problem at all.

It’s correct that the spec allows you to provide separate body items, but it was not at all obvious to many users, so I wanted to reduce the variety of choices for specifying bodies and URIs in the new spec. If you are interested in more details, feel free to browse through the questions on our mailing list.

Personally, I don’t see why we should spend more time in providing support for potential XPath 1.0-only implementations (we still have `http:send-request`). @fgeorges: Are there some of which you are thinking of?

**Comment by fgeorges** [comment]
Not really, just wanted to make sure it was a conscious choice.

BTW there are still a lot of XPath 1.0 out there, e.g. in tools like ESB or WS-*/WSDL/SOAP-related, but I doubt these specs are ever going to cross the path of that audience :-)

**Comment by adamretter** [comment]
I think we can safely close this now. I believe the arguments and rationale for compatibility (and `maps` etc.) has been explained and defended.

If anyone is unhappy, please reopen this...
