### ISSUE TITLE
Supported method for HTTP/1.0

### ISSUE THREAD

**Issue by fgeorges** [expath/expath-cg#93]
The current draft says:

> HTTP 1.0 only supports the HTTP Methods GET, HEAD, and PUT

HTTP/1.0 defines `GET`, `HEAD` and `POST`.  In addition (in an appendix), it defines `PUT`, `DELETE`, `LINK` and `UNLINK`.  Furthermore, the grammar says:

    Method = "GET"
           | "HEAD"
           | "POST"
           | extension-method
    extension-method = token

So you can have anything that is a token.  I would personally simply remove the warning (which is wrong I think) and let the user use whatever they want (the server must respond with a "method not supported" if they use something wrong.)

Speaking of methods, I would accept any "spelling" in inputs from the user (lower- and uppercase), but always return uppercase when it is returned from the module functions (so the user can rely on the output, and we are a bit more lenient with their input.)

**Comment by fgeorges** [comment]
And because I've seen another discussion, closed now, about the need for `http:send-request`, here is a list of registered methods (yes, only the methods officially registered at IANA, I bet there are a lot more out there for specific needs of specific web servers):

http://www.iana.org/assignments/http-methods/http-methods.xhtml

:-)

**Comment by fgeorges** [comment]
Instead of saying specifically that LINK and UNLIKE have not been granted their own function, what about something like this in the introduction instead:

> The function `http:send()` is used to send a HTTP request.  For some of the most frequently used HTTP methods, a specific function is provided as a convenience (`http:get()`, `http:post()`, etc.)

I think it is closer to what is provided in the spec.  If not, we should probably add all of these official methods registered at IANA to explain they do not have a specific function each :-)

- `ACL`
- `BASELINE-CONTROL`
- `BIND`
- `CHECKIN`
- `CHECKOUT`
- `CONNECT`
- `COPY`
- `LABEL`
- `LINK`
- `LOCK`
- `MERGE`
- `MKACTIVITY`
- `MKCALENDAR`
- `MKCOL`
- `MKREDIRECTREF`
- `MKWORKSPACE`
- `MOVE`
- `ORDERPATCH`
- `PATCH`
- `PRI`
- `PROPFIND`
- `PROPPATCH`
- `REBIND`
- `REPORT`
- `SEARCH`
- `UNBIND`
- `UNCHECKOUT`
- `UNLINK`
- `UNLOCK`
- `UPDATE`
- `UPDATEREDIRECTREF`
- `VERSION-CONTROL`

**Comment by ChristianGruen** [comment]
> The function `http:send()` is used to send a HTTP request.  For some of the most frequently used HTTP methods, a specific function is provided as a convenience (`http:get()`, `http:post()`, etc.)

I tried to indicate this by the sentence:

> Convenience functions are provided to simplify basic requests.

I thought it was obvious enough, but maybe I’m wrong?

Regarding your introductory comment…

> Speaking of methods, I would accept any "spelling" in inputs from the user (lower- and uppercase), but always return uppercase when it is returned from the module functions (so the user can rely on the output, and we are a bit more lenient with their input.)

…that’d be fine for me as well. I’m wondering if an implementation should convert the method to uppercase before sending it to the server?

**Comment by fgeorges** [comment]
> I thought it was obvious enough, but maybe I’m wrong?

Not, it is clear.  But the following (about support of HTTP/1.0) is not necessary then (just by being there, it seems to imply the opposite):

> Although we do not provide explicit functions for the LINK and UNLINK HTTP methods, as in practice these methods do not appear to be widely used, they are still supported via the http:send function. 

And I'd say yes for:

> an implementation should convert the method to uppercase

**Comment by adamretter** [comment]
I think this is unneccesary with regards any changes here.

LINK and UNLINK are explicitly in the HTTP 1.0 spec that is referenced. As are DELETE and PUT, which are in the appendix as @fgeorges earlier pointed out. Hence their mention in our spec.

The IANA methods are a completely separate thing, not mentioned in the HTTP specs, which we need not worry about, or confuse anyone with. People can still use them via http:send if they want to.

Otherwise... next we will end up listing all the IANA media types too :-( This is a bad thing.

**Comment by fgeorges** [comment]
That's my point: we do not need to mention any specific method at all.  Not these from IANA, not LINK/UNLINK either.  These were just not lucky enough to have their own function, so one has to use http:send() for them.  But mentioning them gives them a specific status.  What about the HTTP/1.1 method CONNECT, for instance?

I think that given the following sentence, mentioning some methods explicitly as not having their own function because there are not used enough, is quite confusing:

> Convenience functions are provided to simplify basic requests.

**Comment by ChristianGruen** [comment]
Should we continue discussing this issue, or just close it and regard it as editorial note that we’ll keep in mind for the final polishing of the spec?

**Comment by adamretter** [comment]
Im happy with it as is. So editorial oversight is fine for me ;-)

**Comment by ChristianGruen** [comment]
@fgeorges: Any objections?

**Comment by adamretter** [comment]
@fgeorges @ChristianGruen As we have had no response I am going to close this. Feel free to reopen if needed.
